refresh patches

diff --git a/debian/patches/0004-sysvinit-lsb-functions.patch b/debian/patches/0004-sysvinit-lsb-functions.patch
--- a/debian/patches/0004-sysvinit-lsb-functions.patch
+++ b/debian/patches/0004-sysvinit-lsb-functions.patch
@@ -4,37 +4,75 @@ Description: Correcting wrong LSB functions in sysvinit script (Closes: #740066)
  https://github.com/lxc/lxc/issues/310,
  and https://github.com/lxc/lxc/issues/311.
 
-diff -Naurp lxc.orig/config/init/sysvinit/lxc.in lxc/config/init/sysvinit/lxc.in
---- lxc.orig/config/init/sysvinit/lxc.in
-+++ lxc/config/init/sysvinit/lxc.in
-@@ -49,8 +49,8 @@ OPTIONS=
- STOPOPTS="-a -s"
+diff --git a/config/init/sysvinit/lxc-containers.in b/config/init/sysvinit/lxc-containers.in
+index bc93322..32c2fe7 100644
+--- a/config/init/sysvinit/lxc-containers.in
++++ b/config/init/sysvinit/lxc-containers.in
+@@ -16,25 +16,17 @@
+ sysconfdir="@SYSCONFDIR@"
  
  # Source function library.
 -test ! -r "$sysconfdir"/rc.d/init.d/functions ||
 -        . "$sysconfdir"/rc.d/init.d/functions
+-
+-# provide action() fallback
+-if ! type action >/dev/null 2>&1; then
+-    # Real basic fallback for sysvinit "action" verbage.
+-    action() {
+-        echo -n "$1	"
+-        shift
+-        "$@" && echo "OK" || echo "Failed"
+-    }
+-fi
 +test ! -r /lib/lsb/init-functions ||
 +        . /lib/lsb/init-functions
  
- # Source any configurable options
- test ! -r "$sysconfdir"/sysconfig/lxc ||
-@@ -105,7 +105,8 @@ case "$1" in
- 	# Start containers
- 	wait_for_bridge
- 	# Start autoboot containers first then the NULL group "onboot,".
--	action $"Starting LXC autoboot containers: " "$bindir"/lxc-autostart $OPTIONS $BOOTGROUPS
-+	log_daemon_msg "Starting LXC autoboot containers: "
-+	"$bindir"/lxc-autostart $OPTIONS $BOOTGROUPS
- 	touch "$localstatedir"/lock/subsys/lxc
- 	;;
-   stop)
-@@ -117,7 +118,8 @@ case "$1" in
- 	# The stop is serialized and can take excessive time.  We need to avoid
- 	# delaying the system shutdown / reboot as much as we can since it's not
- 	# parallelized...  Even 5 second timout may be too long.
--	action $"Stopping LXC containers: " "$bindir"/lxc-autostart $STOPOPTS $SHUTDOWNDELAY
-+	log_daemon_msg "Stopping LXC containers: "
-+	"$bindir"/lxc-autostart $STOPOPTS $SHUTDOWNDELAY
- 	rm -f "$localstatedir"/lock/subsys/lxc
- 	;;
-   restart|reload|force-reload)
+ start() {
+-    action $"Starting LXC autoboot containers: " @LIBEXECDIR@/lxc/lxc-containers start
++    log_daemon_msg "Starting LXC autoboot containers: "
++    @LIBEXECDIR@/lxc/lxc-containers start
+ }
+ 
+ stop() {
+-    action $"Stopping LXC containers: " @LIBEXECDIR@/lxc/lxc-containers stop
++    log_daemon_msg "Stopping LXC containers: "
++    @LIBEXECDIR@/lxc/lxc-containers stop
+ }
+ 
+ # See how we were called.
+diff --git a/config/init/sysvinit/lxc-net.in b/config/init/sysvinit/lxc-net.in
+index f6892c1..89675e5 100644
+--- a/config/init/sysvinit/lxc-net.in
++++ b/config/init/sysvinit/lxc-net.in
+@@ -16,25 +16,17 @@
+ sysconfdir="@SYSCONFDIR@"
+ 
+ # Source function library.
+-test ! -r "$sysconfdir"/rc.d/init.d/functions ||
+-        . "$sysconfdir"/rc.d/init.d/functions
+-
+-# provide action() fallback
+-if ! type action >/dev/null 2>&1; then
+-    # Real basic fallback for sysvinit "action" verbage.
+-    action() {
+-        echo -n "$1	"
+-        shift
+-        "$@" && echo "OK" || echo "Failed"
+-    }
+-fi
++test ! -r /lib/lsb/init-functions ||
++        . /lib/lsb/init-functions
+ 
+ start() {
+-    action $"Starting LXC network bridge: " @LIBEXECDIR@/lxc/lxc-net start
++    log_daemon_msg "Starting LXC network bridge: "
++    @LIBEXECDIR@/lxc/lxc-net start
+ }
+ 
+ stop() {
+-    action $"Stopping LXC network bridge: " @LIBEXECDIR@/lxc/lxc-net stop
++    log_daemon_msg "Stopping LXC network bridge: "
++    @LIBEXECDIR@/lxc/lxc-net stop
+ }
+ 
+ # See how we were called.
